name = "shitcoin"
main = "worker.dist.js"
compatibility_date = "2024-01-01"
workers_dev = true

[build]
command = "/usr/local/bin/node build.js"

[[routes]]
pattern = "shitcoin.io/*"
zone_name = "shitcoin.io"
